Conference/Conference/Controllers/SpeakersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Conference.Domain.Entities;
using Conference.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Conference.Controllers
{
    
    public class SpeakersController : Controller
    {
        private readonly ISpeakerService speakerService;

        public SpeakersController(ISpeakerService speakerService)
        {
            this.speakerService = speakerService;
        }

        // GET: Speakers
        public ActionResult Index()
        {
            var allSpeakers = speakerService.GetAllSpeakers();
            return View(allSpeakers);
        }

        // GET: Speakers/Details/5
        public ActionResult Details(int id)
        {
            Speakers speaker = speakerService.GetSpeakerById(id);
            return View(speaker);
        }

        // GET: Speakers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Speakers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Speakers model)
        {
            if (ModelState.IsValid)
            {
                Speakers addedSpeaker = speakerService.AddSpeaker(model);
                if (addedSpeaker != null)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        // GET: Speakers/Edit/5
        public ActionResult Edit(int id)
        {
            Speakers speakerToEdit = speakerService.GetSpeakerById(id);
            return View(speakerToEdit);
        }

        // POST: Speakers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Speakers model)
        {
            if(ModelState.IsValid)
            {
                var existingSpeaker = speakerService.GetSpeakerById(id);
                TryUpdateModelAsync(existingSpeaker);
                speakerService.UpdateSpeaker(existingSpeaker);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        // GET: Speakers/Delete/5
        public ActionResult Delete(int id)
        {
            Speakers speakerToDelete = speakerService.GetSpeakerById(id);
            speakerService.DeleteSpeaker(speakerToDelete);
            return RedirectToAction(nameof(Index));
        }

        // POST: Speakers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Conference/Conference/Controllers/SponsorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Conference.Models;
using Conference.Domain.Entities;
using Conference.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Omu.ValueInjecter;

namespace Conference.Controllers
{
    
    public class SponsorsController : Controller
    {
        private readonly ISponsorsService sponsorsService;

        public SponsorsController(ISponsorsService sponsorsService)
        {
            this.sponsorsService = sponsorsService;
        }

        // GET: Sponsors
        public ActionResult Index()
        {
            List<Sponsors> sponsors;
            sponsors = sponsorsService.GetAllSponsors();
            return View(sponsors);
        }

        // GET: Sponsors/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Sponsors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sponsors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SponsorsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Sponsors sponsor = new Sponsors();
                sponsor.InjectFrom(model);
                Sponsors addedSponsor = sponsorsService.AddSponsors(sponsor);
                if(addedSponsor!=null)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Name", "It seems there is an error about the entity...");
                    return View(model);
                }
            }
            else
            {
                ModelState.AddModelError("Name", "It seems there is an error on the model...");
                return View(model);
            }
        }

        // GET: Sponsors/Edit/5
        public ActionResult Edit(int id)
        {
            Sponsors sponsorToEdit = sponsorsService.GetSponsorById(id);
            if(sponsorToEdit!=null)
            {
                SponsorsViewModel model = new SponsorsViewModel();
                model.InjectFrom(sponsorToEdit);
                return View(model);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
            
        }

        // POST: Sponsors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SponsorsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Sponsors sponsorToUpdate = new Sponsors();
                sponsorToUpdate.InjectFrom(model);
                TryUpdateModelAsync(sponsorToUpdate);
                sponsorsService.UpdateSponsors(sponsorToUpdate);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("Name", "It seems there is a problem with the model...");
                return View(model);
            }
        }

        // GET: Sponsors/Delete/5
        public ActionResult Delete(int id)
        {
            Sponsors sponsorToDelete = sponsorsService.GetSponsorById(id);
            if(sponsorToDelete!=null)
            {
                sponsorsService.DeleteSponsor(sponsorToDelete);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Sponsors/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Conference/Conference/Controllers/WorkshopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Conference.Domain.Entities;
using Conference.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Conference.Controllers
{
    
    public class WorkshopsController : Controller
    {
        private readonly IWorkshopService workshopService;

        public WorkshopsController(IWorkshopService workshopService)
        {
            this.workshopService = workshopService;
        }
        // GET: Workshops
        public ActionResult Index()
        {
            var allWorkshops = workshopService.GetAllWorkshops();
            return View(allWorkshops);
        }

        // GET: Workshops/Details/5
        public ActionResult Details(int id)
        {
            Workshops model;
            model = workshopService.GetWorkshopById(id);
            return View(model);
        }

        // GET: Workshops/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Workshops/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Workshops model)
        {
            if(ModelState.IsValid)
            {
                Workshops addedWorkshop = workshopService.AddWorkshop(model);
                if (addedWorkshop==null)
                {
                    return View(model);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                return View(model);
            }
        }

        // GET: Workshops/Edit/5
        public ActionResult Edit(int id)
        {
            Workshops editedWorkshop;
            editedWorkshop = workshopService.GetWorkshopById(id);
            return View(editedWorkshop);
        }

        // POST: Workshops/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Workshops model)
        {
            if (ModelState.IsValid)
            {
                Workshops workshopToUpdate = workshopService.GetWorkshopById(id);
                TryUpdateModelAsync(workshopToUpdate);
                Workshops updatedWorkshop= workshopService.UpdateWorkshop(workshopToUpdate);
                if (updatedWorkshop != null)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        // GET: Workshops/Delete/5
        public ActionResult Delete(int id)
        {
            Workshops workshopToDelete = workshopService.GetWorkshopById(id);
            workshopService.DeleteWorkshop(workshopToDelete);
            return RedirectToAction(nameof(Index));
        }

        // POST: Workshops/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Conference/Conference/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Conference</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-default bg-mv">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav justify-content-end d-flex flex-fill">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Agenda <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Speakers" asp-action="Index">Speakers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Sponsors" asp-action="Index">Sponsors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Workshops" asp-action="Index">Workshops</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Conference - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>