Conference/Conference/Areas/Admin/Controllers/EditionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Conference.Domain.Entities;
using Conference.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Conference.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EditionController : Controller
    {
        private readonly IEditionService editionsService;

        public EditionController(IEditionService editionsService)
        {
            this.editionsService = editionsService;
        }

        // GET: Edition
        public ActionResult Index()
        {
            var allEditions = editionsService.GetAllEditions();
            return View(allEditions);
        }

        // GET: Edition/Details/5
        public ActionResult Details(int id)
        {
            Editions edition = editionsService.GetEditionById(id);
            return View(edition);
        }

        // GET: Edition/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Edition/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Editions model)
        {
            if(ModelState.IsValid)
            {
                Editions addedEdition = editionsService.AddEdition(model);
                if (addedEdition != null)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

        // GET: Edition/Edit/5
        public ActionResult Edit(int id)
        {
            var editionToEdit = editionsService.GetEditionById(id);
            return View(editionToEdit);
        }

        // POST: Edition/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Editions model)
        {
            if(ModelState.IsValid)
            {
                var existingEdition = editionsService.GetEditionById(id);
                TryUpdateModelAsync(existingEdition);
                editionsService.Update(existingEdition);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(model);
            }
        }

        // GET: Edition/Delete/5
        public ActionResult Delete(int id)
        {
            Editions editionToDelete;
            editionToDelete = editionsService.GetEditionById(id);
            if (editionToDelete != null)
            {
                editionsService.Delete(editionToDelete);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Edition/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Conference/Conference/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Conference.Models;

namespace Conference.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Conference/Conference/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page by Tavy";
}

<link rel="stylesheet" type="text/css" href="~/css/site.css" />


<div class="jumbotron-fluid">
    <img class="banner" src="~/images/tech.jpg" />
    <div class="text-center">
        <p id="demo"></p>
        <h1 class="year">2020</h1>
        <h3 class="location">22 November 2019 |Iasi, Romania</h3>
        <div class="btns-container">
            <a href="https://www.bilete.ro/" target="_blank" class="btn btn-large btn-main">Register</a>
        </div>
    </div>
</div>

@**@
<div class="container-fluid">
    <p>Speakers:</p>
    <div class="row">
        <div class="col-md-4 col-4">
            <a class="tavyA"href="http://www.hotnews.ro">CV</a>
            <img class="details" src="https://dndays.blob.core.windows.net/img/91/alex-thissen.png" />
            
        </div>
        <div class="col-md-4 col-4">
            <a class="tavyA" href="http://www.hotnews.ro">CV</a>
            <img class="details" src="https://dndays.blob.core.windows.net/img/91/alex-thissen.png" />
        </div>
        <div class="col-md-4 col-4">
            <a class="tavyA" href="http://www.hotnews.ro">CV</a>
            <img class="details" src="https://dndays.blob.core.windows.net/img/91/alex-thissen.png" />
        </div>
    </div>
</div>
@**@

<div class="container">
    <div class="row-parent">
        <p class="announcement">Stay Tuned for a Major Announcement!<p>
    </div>
</div>


@*<div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>

    <div>
        <a asp-controller="Edition" asp-action="Index" asp-area="Admin">Editions List</a>
        <p><a href="http://localhost:12922/Admin/edition">Edtions List</a></p>
    </div>

    @*<div>
        <p><a href="http://localhost:12922/admin/edition/create">Admin/Edition/Create</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/Admin/Edition/Details/1">Admin/Edition/Details/1</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/speakers">Speakers List</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/speakers/create">Admin/Speakers/Create</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/talks">Talks List</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/talks/create">Admin/Talks/Create</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/workshops">Workshops List</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/workshops/create">Admin/Workshops/Create</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/sponsortypes">SponsorTypes List</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/sponsorTypes/create">Admin/SponsorTypes/Create</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/sponsors">Sponsor List</a></p>
    </div>

    <div>
        <p><a href="http://localhost:12922/admin/sponsors/create">Admin/Sponsors/Create</a></p>
    </div>*@